/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author rubco
 */
public class ActividadesPanel extends javax.swing.JPanel {
    
    public JTable tablaActividad;
    public JButton nuevaActividad;
    public JButton bajaActividad;
    public JButton actualizacionActividad;

    /**
     * Creates new form ActividadesPanel
     */
    public ActividadesPanel() {
        initComponents();
        this.setLayout(null);
        JLabel titulo = new JLabel("Gestion de Actividades");
        titulo.setBounds(30, 30, 300, 30);
        titulo.setFont(new Font("Segoe UI", Font.PLAIN, 24));
        add(titulo);
        
        tablaActividad = new JTable();
        
        JScrollPane scrollPane = new JScrollPane(tablaActividad);
        scrollPane.setBounds(30, 70, 1440, 300);
        
        scrollPane.getViewport().setBorder(null);
        add(scrollPane);
        
         nuevaActividad = new JButton("Nueva Actividad");
        bajaActividad = new JButton("Baja Actividad");
        actualizacionActividad = new JButton("Actualización Actividad");

        nuevaActividad.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        bajaActividad.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        actualizacionActividad.setFont(new Font("Segoe UI", Font.PLAIN, 15));

        nuevaActividad.setBounds(30, 375, 150, 30);
        bajaActividad.setBounds(185, 375, 150, 30);
        actualizacionActividad.setBounds(340, 375, 200, 30);

        add(nuevaActividad);
        add(bajaActividad);
        add(actualizacionActividad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

