/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author rubco
 */
public class InicioPanel extends javax.swing.JPanel {

    /**
     * Creates new form IncioPanel
     */
    private Image fondo;
    
    public InicioPanel() {
        initComponents();
        
        fondo = new ImageIcon(getClass().getResource("/Imagenes/trueFit.jpg")).getImage();
        
        repaint();
        
        JLabel tru = new JLabel("True");
        tru.setFont(new Font("Segoe UI Bold", Font.BOLD, 100));
        tru.setForeground(new Color(51, 204, 255));
        tru.setBounds(550, 210, 250, 120);
        add(tru);
        
        JLabel fit = new JLabel("Fit");
        fit.setFont(new Font("Segoe UI Light", Font.PLAIN, 100));
        fit.setForeground(Color.WHITE);
        fit.setBounds(770, 210, 150, 120);
        add(fit);
        
        //51,204,255
        
        
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        
        Graphics2D g2d = (Graphics2D) g;
        
        g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        g2d.drawImage(fondo, 0,0, this.getWidth(), this.getHeight(), this);
        
    }
    
    
    
    

    /**<W
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1500, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
