/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author rubco
 */
public class InscripcionesPanel extends javax.swing.JPanel {

    public JComboBox<String> sociosCombo;
    public JScrollPane scrollPane1;
    public JScrollPane scrollPane2;
    public JButton altaBoton;
    public JButton bajaBoton;
    public JTable tabla1;
    public JTable tabla2;

    /**
     * Creates new form InscripcionesPanel
     */
    public InscripcionesPanel() {
        initComponents();
        initComponents();
        this.setLayout(null);
        JLabel titulo = new JLabel("Inscripciones");
        titulo.setBounds(30, 30, 300, 30);
        titulo.setFont(new Font("Segoe UI", Font.PLAIN, 24));
        add(titulo);

        JLabel socios = new JLabel("Socios");
        socios.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        socios.setBounds(30, 70, 100, 20);
        add(socios);
        
        JLabel apuntado = new JLabel("Actividades en la que el socio esta apuntado");
        apuntado.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        apuntado.setBounds(35, 140, 400, 20);
        add(apuntado);
        
        JLabel noApuntado = new JLabel("Actividades en la que el socio no esta apuntado");
        noApuntado.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        noApuntado.setBounds(885, 140, 400, 20);
        add(noApuntado);

        sociosCombo = new JComboBox<>();
        sociosCombo.setBounds(30, 92, 200, 25);

        tabla1 = new JTable();
        scrollPane1 = new JScrollPane(tabla1); // Pasar la tabla al constructor
        scrollPane1.setBounds(30, 170, 550, 350);
        add(scrollPane1);

        tabla2 = new JTable();
        scrollPane2 = new JScrollPane(tabla2); // Pasar la tabla al constructor
        scrollPane2.setBounds(880, 170, 550, 350);
        add(scrollPane2);
        
        
        altaBoton = new JButton("Alta Actividad");
        altaBoton.setBounds(655, 270, 150, 30);
        altaBoton.setEnabled(false);
        add(altaBoton);
        
        
        bajaBoton = new JButton("Baja Actividad");
        bajaBoton.setBounds(655, 370, 150, 30);
        bajaBoton.setEnabled(false);
        add(bajaBoton);

        add(sociosCombo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
