/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author rubco
 */
public class MonitorPanel extends javax.swing.JPanel {

    public JButton nuevoMonitor;
    public JButton bajaMonitor;
    public JButton actualizacionMonitor;

    /**
     * Creates new form MonitorPanel
     */
    public MonitorPanel() {
        initComponents();
        this.setLayout(null);
        JLabel titulo = new JLabel("Gestion de Monitores");
        titulo.setBounds(30, 30, 300, 30);
        titulo.setFont(new Font("Segoe UI", Font.PLAIN, 24));
        add(titulo);

        tablaMonitor = new JTable();
        tablaMonitor.setFillsViewportHeight(true);

        JScrollPane scrollPane = new JScrollPane(tablaMonitor);
        scrollPane.setBounds(30, 70, 1440, 291);

        scrollPane.getViewport().setBorder(null);
        add(scrollPane);

        nuevoMonitor = new JButton("Nuevo Monitor");
        bajaMonitor = new JButton("Baja Monitor");
        actualizacionMonitor = new JButton("Actualización Monitor");

        nuevoMonitor.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        bajaMonitor.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        actualizacionMonitor.setFont(new Font("Segoe UI", Font.PLAIN, 15));

        nuevoMonitor.setBounds(30, 375, 150, 30);
        bajaMonitor.setBounds(185, 375, 150, 30);
        actualizacionMonitor.setBounds(340, 375, 200, 30);

        add(nuevoMonitor);
        add(bajaMonitor);
        add(actualizacionMonitor);

    }

    public JTable tablaMonitor;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
