/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author rubco
 */
public class SocioPanel extends javax.swing.JPanel {
    
    public JTable tablaSocio;
    
    public JButton nuevoSocio;
    public JButton bajaSocio;
    public JButton actualizacionSocio;

    /**
     * Creates new form SocioPanel
     */
    public SocioPanel() {
        initComponents();
        JLabel titulo = new JLabel("Gestion de Socios");
        titulo.setBounds(30, 30, 300, 30);
        titulo.setFont(new Font("Segoe UI", Font.PLAIN, 24));
        add(titulo);
        
        tablaSocio = new JTable();
        
        JScrollPane scrollPane = new JScrollPane(tablaSocio);
        scrollPane.setBounds(30, 70, 1440, 300);
        
        scrollPane.getViewport().setBorder(null);
        add(scrollPane);
        
        
        
        nuevoSocio = new JButton("Nuevo Socio");
        bajaSocio = new JButton("Baja Socio");
        actualizacionSocio = new JButton("Actualización Socio");
        
        nuevoSocio.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        bajaSocio.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        actualizacionSocio.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        
        nuevoSocio.setBounds(30, 375, 150, 30);
        bajaSocio.setBounds(185, 375, 150, 30);
        actualizacionSocio.setBounds(340, 375, 200, 30);
        
        add(nuevoSocio);
        add(bajaSocio);
        add(actualizacionSocio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
