/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JFrame;

/**
 *
 * @author rubco
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        inicioMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        monitorMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        socioMenu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        actividadMenu = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        salirMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 1000));

        inicioMenu.setText("Inicio");

        jMenuItem2.setText("Ir a Inicio");
        jMenuItem2.setActionCommand("InicioMenu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        inicioMenu.add(jMenuItem2);

        jMenuBar1.add(inicioMenu);

        jMenu2.setText("Monitores");

        monitorMenu.setText("Gestion Monitores");
        monitorMenu.setActionCommand("GestionMonitores");
        monitorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorMenuActionPerformed(evt);
            }
        });
        jMenu2.add(monitorMenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Socios");

        socioMenu.setText("Gestion Socios");
        socioMenu.setActionCommand("GestionSocios");
        jMenu3.add(socioMenu);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Actividades");

        actividadMenu.setText("Gestion de Actividades");
        actividadMenu.setActionCommand("GestionActividades");
        jMenu4.add(actividadMenu);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");

        salirMenu.setText("Salir");
        salirMenu.setActionCommand("SalirMenu");
        salirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuActionPerformed(evt);
            }
        });
        jMenu5.add(salirMenu);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monitorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monitorMenuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void salirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem actividadMenu;
    public javax.swing.JMenu inicioMenu;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem monitorMenu;
    public javax.swing.JMenuItem salirMenu;
    public javax.swing.JMenuItem socioMenu;
    // End of variables declaration//GEN-END:variables
}
